#!/usr/bin/python3
"""
This script factorizes as many numbers as possible from a file into a product of two smaller numbers.
Usage: ./factors <file>
"""

import sys
from math import isqrt


def factorize(numb):
    """
    Factorizes a number into a product of two smaller numbers.

    Args:
    numb (int): The numbers to be factorized

    Returns:
    str: The string representation of the factorization in the format "n=p*q"
    """
    for i in range(2, isqrt(numb) + 1):
        if numb % i == 0:
            return f"{numb}={i}*{numb//i}"

    return f"{numb}={numb}*1"


def main():
    """Main function to read the file and factorize numbers."""
    if len(sys.argv) != 2:
        sys.exit(1)

    try:
        with open(sys.argv[1], 'r', encoding='utf-8') as file:
            for line in file:
                numb = int(line.strip())
                print(factorize(numb))
    except FileNotFoundError:
        sys.exit(1)
    except ValueError as e:
        sys.exit(1)


if __name__ == "__main__":
    main()

