#!/usr/bin/env bash

factorize() {
    n=$1
    for i in $(seq 2 $(echo "sqrt($n)" | bc)); do
        if (( n % i == 0 )); then
            echo "$n=$i*$((n/i))"
            return
        fi
    done
    echo "$n=$n*1"
}

if [ $# -ne 1 ]; then
    echo "Usage: $0 <file>"
    exit 1
fi

while read -r number; do
    factorize "$number"
done < "$1"
